language: cpp

sudo: required

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y make
  - sudo apt-get install -y g++
  - sudo apt-get install -y automake
  - sudo apt-get install -y libtool
  - sudo apt-get install -y libfreetype6-dev
  - sudo apt-get install -y libfontconfig1-dev
  - sudo apt-get install -y libgl1-mesa-dev
  - sudo apt-get install -y libxrender-dev
  - sudo apt-get install -y libasound2-dev
  - sudo apt-get install -y doxygen
  - sudo apt-get install -y cmake
  - sudo apt-get install -y liblua5.1-0-dev
  - sudo apt-get install -y git

before_script:
  - git clone https://github.com/sphair/ClanLib.git
  - cd ClanLib
  - git checkout 3.0-stable
  - ./autogen.sh
  - ./configure
  - travis_wait 60 make --silent -j8
  - sudo make install --silent
  - cd ..
  - rm -rf ClanLib

script:
  - cmake .
  - make -j4
