ClanLib: CL_Super_1< RetVal, Param1 > Class Template Reference
CL_Super_1< RetVal, Param1 > Class Template Reference
[clanCore Signals]
#include <virtual_function_1.h>
Public Member Functions
RetVal invoke (Param1 param1)
bool is_invokable () const
bool is_null () const
Public Attributes
std::vector< CL_SharedPtr
< CL_SlotCallback >
>::reverse_iterator it_end
std::vector< CL_SharedPtr
< CL_SlotCallback >
>::reverse_iterator it_super
Detailed Description
template<typename RetVal, class Param1>
class CL_Super_1< RetVal, Param1 >
(Internal ClanLib Class)
Member Function Documentation
template<typename RetVal, class Param1> RetVal CL_Super_1< RetVal, Param1 >::invoke (Param1 param1) [inline]
References CL_Super_1< RetVal, Param1 >::it_end, and CL_Super_1< RetVal, Param1 >::it_super.
Referenced by CL_VirtualFunction_1< RetVal, Param1 >::invoke().
template<typename RetVal, class Param1> bool CL_Super_1< RetVal, Param1 >::is_invokable () const [inline]
References CL_Super_1< RetVal, Param1 >::is_null().
template<typename RetVal, class Param1> bool CL_Super_1< RetVal, Param1 >::is_null () const [inline]
References CL_Super_1< RetVal, Param1 >::it_end, and CL_Super_1< RetVal, Param1 >::it_super.
Referenced by CL_Super_1< RetVal, Param1 >::is_invokable().
Member Data Documentation
template<typename RetVal, class Param1> std::vector< CL_SharedPtr<CL_SlotCallback> >::reverse_iterator CL_Super_1< RetVal, Param1 >::it_end
Referenced by CL_VirtualFunction_1< RetVal, Param1 >::invoke(), CL_Super_1< RetVal, Param1 >::invoke(), and CL_Super_1< RetVal, Param1 >::is_null().
template<typename RetVal, class Param1> std::vector< CL_SharedPtr<CL_SlotCallback> >::reverse_iterator CL_Super_1< RetVal, Param1 >::it_super
Referenced by CL_VirtualFunction_1< RetVal, Param1 >::invoke(), CL_Super_1< RetVal, Param1 >::invoke(), and CL_Super_1< RetVal, Param1 >::is_null().
The documentation for this class was generated from the following file:
virtual_function_1.h