ClanLib: CL_SoundProviderType_Register< SoundProviderClass > Class Template Reference
CL_SoundProviderType_Register< SoundProviderClass > Class Template Reference
[clanSound Sound Providers]
Class template to register a sound provider type.
#include <soundprovider_type_register.h>
Public Member Functions
Construction
CL_SoundProviderType_Register (const CL_String &type)
Registers sound provider type in the CL_SoundProviderFactory.
Operations
virtual CL_SoundProvider * load (const CL_String &filename, bool stream, const CL_VirtualDirectory &directory)
Called to load static with this sound provider type.
virtual CL_SoundProvider * load (CL_IODevice &file, bool stream)
Called to load static with this sound provider type.
Detailed Description
template<class SoundProviderClass>
class CL_SoundProviderType_Register< SoundProviderClass >
Class template to register a sound provider type.
Constructor & Destructor Documentation
template<class SoundProviderClass > CL_SoundProviderType_Register< SoundProviderClass >::CL_SoundProviderType_Register (const CL_String & type) [inline]
Registers sound provider type in the CL_SoundProviderFactory.
References CL_SoundProviderType::CL_SoundProviderType(), and CL_SoundProviderType_Register< SoundProviderClass >::load().
Member Function Documentation
template<class SoundProviderClass > virtual CL_SoundProvider* CL_SoundProviderType_Register< SoundProviderClass >::load (const CL_String & filename, bool stream, const CL_VirtualDirectory & directory) [inline, virtual]
Called to load static with this sound provider type.
Implements CL_SoundProviderType.
Referenced by CL_SoundProviderType_Register< SoundProviderClass >::CL_SoundProviderType_Register().
template<class SoundProviderClass > virtual CL_SoundProvider* CL_SoundProviderType_Register< SoundProviderClass >::load (CL_IODevice & file, bool stream) [inline, virtual]
Called to load static with this sound provider type.
Implements CL_SoundProviderType.
The documentation for this class was generated from the following file:
soundprovider_type_register.h