ClanLib: CL_Super_2< RetVal, Param1, Param2 > Class Template Reference
CL_Super_2< RetVal, Param1, Param2 > Class Template Reference
[clanCore Signals]
#include <virtual_function_2.h>
Public Member Functions
RetVal invoke (Param1 param1, Param2 param2)
bool is_invokable () const
bool is_null () const
Public Attributes
std::vector< CL_SharedPtr
< CL_SlotCallback >
>::reverse_iterator it_end
std::vector< CL_SharedPtr
< CL_SlotCallback >
>::reverse_iterator it_super
Detailed Description
template<typename RetVal, class Param1, class Param2>
class CL_Super_2< RetVal, Param1, Param2 >
(Internal ClanLib Class)
Member Function Documentation
template<typename RetVal, class Param1, class Param2> RetVal CL_Super_2< RetVal, Param1, Param2 >::invoke (Param1 param1, Param2 param2) [inline]
References CL_Super_2< RetVal, Param1, Param2 >::it_end, and CL_Super_2< RetVal, Param1, Param2 >::it_super.
Referenced by CL_VirtualFunction_2< RetVal, Param1, Param2 >::invoke().
template<typename RetVal, class Param1, class Param2> bool CL_Super_2< RetVal, Param1, Param2 >::is_invokable () const [inline]
References CL_Super_2< RetVal, Param1, Param2 >::is_null().
template<typename RetVal, class Param1, class Param2> bool CL_Super_2< RetVal, Param1, Param2 >::is_null () const [inline]
References CL_Super_2< RetVal, Param1, Param2 >::it_end, and CL_Super_2< RetVal, Param1, Param2 >::it_super.
Referenced by CL_Super_2< RetVal, Param1, Param2 >::is_invokable().
Member Data Documentation
template<typename RetVal, class Param1, class Param2> std::vector< CL_SharedPtr<CL_SlotCallback> >::reverse_iterator CL_Super_2< RetVal, Param1, Param2 >::it_end
Referenced by CL_VirtualFunction_2< RetVal, Param1, Param2 >::invoke(), CL_Super_2< RetVal, Param1, Param2 >::invoke(), and CL_Super_2< RetVal, Param1, Param2 >::is_null().
template<typename RetVal, class Param1, class Param2> std::vector< CL_SharedPtr<CL_SlotCallback> >::reverse_iterator CL_Super_2< RetVal, Param1, Param2 >::it_super
Referenced by CL_VirtualFunction_2< RetVal, Param1, Param2 >::invoke(), CL_Super_2< RetVal, Param1, Param2 >::invoke(), and CL_Super_2< RetVal, Param1, Param2 >::is_null().
The documentation for this class was generated from the following file:
virtual_function_2.h