ClanLib: CL_String8 Class Reference
CL_String8 Class Reference
[clanCore Text]
String container template.
#include <string8.h>
Public Types
typedef char char_type
typedef const char * const_iterator
typedef char * iterator
typedef unsigned int size_type
Public Member Functions
CL_String8 ()
CL_String8 (const std::string &source)
Constructs a StringContainer.
CL_String8 (const CL_StringData8 &source)
Constructs a StringContainer.
CL_String8 (const wchar_t *wc_str, size_type length)
Constructs a StringContainer.
CL_String8 (size_type n, char c)
Constructs a StringContainer.
CL_String8 (const char *c_str)
Constructs a StringContainer.
CL_String8 (const CL_String8 &source)
Constructs a StringContainer.
CL_String8 (const char *c_str, size_type length)
Constructs a StringContainer.
CL_String8 (const wchar_t *wc_str)
Constructs a StringContainer.
~CL_String8 ()
CL_String8 & append (const CL_StringData8 &s, size_type pos, size_type n)
Append.
CL_String8 & append (const char *s)
CL_String8 & append (const char *s, size_type n)
Append.
CL_String8 & append (const wchar_t *s)
Append.
CL_String8 & append (const wchar_t *s, size_type n)
Append.
CL_String8 & append (size_type n, char c)
Append.
CL_String8 & append (const CL_StringData8 &s)
Append.
CL_String8 & assign (const CL_StringData8 &s)
CL_String8 & assign (const CL_StringData8 &s, size_type pos, size_type n)
Assign.
CL_String8 & assign (const char *s, size_type n)
Assign.
CL_String8 & assign (const char *s)
Assign.
CL_String8 & assign (size_type n, char c)
Assign.
iterator begin ()
Begin.
const_iterator begin () const
Begin.
const char * c_str () const
size_type capacity () const
Capacity.
void clear ()
Clear.
int compare (size_type pos, size_type n, const CL_StringData8 &s, size_type pos1, size_type n1) const
Compare.
int compare (const CL_StringData8 &s) const
Compare.
int compare (size_type pos, size_type n, const CL_StringData8 &s) const
Compare.
int compare (const char *s) const
Compare.
int compare (size_type pos, size_type n, const char *s, size_type len=npos) const
Compare.
size_type copy (char *buf, size_type n, size_type pos=0) const
Copy.
const char * data () const
char * data ()
Data.
bool empty () const
Empty.
iterator end ()
End.
const_iterator end () const
End.
iterator erase (iterator p)
Erase.
iterator erase (iterator first, iterator last)
Erase.
CL_String8 & erase (size_type pos=0, size_type n=CL_StringData8::npos)
Erase.
size_type find (const CL_StringData8 &s, size_type pos=0) const
Find.
size_type find (const char *s, size_type pos, size_type n) const
Find.
size_type find (const char *s, size_type pos=0) const
Find.
size_type find (char c, size_type pos=0) const
Find.
size_type find_first_not_of (const CL_StringData8 &s, size_type pos=0) const
Find first not of.
size_type find_first_not_of (const char *s, size_type pos, size_type n) const
Find first not of.
size_type find_first_not_of (const char *s, size_type pos=0) const
Find first not of.
size_type find_first_not_of (char c, size_type pos=0) const
Find first not of.
size_type find_first_of (const char *s, size_type pos=0) const
Find first of.
size_type find_first_of (const CL_StringData8 &s, size_type pos=0) const
Find first of.
size_type find_first_of (char c, size_type pos=0) const
Find first of.
size_type find_first_of (const char *s, size_type pos, size_type n) const
Find first of.
size_type find_last_not_of (const char *s, size_type pos, size_type n) const
Find last not of.
size_type find_last_not_of (const CL_StringData8 &s, size_type pos=npos) const
Find last not of.
size_type find_last_not_of (const char *s, size_type pos=npos) const
Find last not of.
size_type find_last_not_of (char c, size_type pos=npos) const
Find last not of.
size_type find_last_of (const CL_StringData8 &s, size_type pos=npos) const
Find last of.
size_type find_last_of (const char *s, size_type pos, size_type n) const
Find last of.
size_type find_last_of (const char *s, size_type pos=npos) const
Find last of.
size_type find_last_of (char c, size_type pos=npos) const
Find last of.
iterator insert (iterator pos, const char &item)
Insert.
void insert (iterator pos, size_type num_copies, const char &item)
Insert.
CL_String8 & insert (size_type pos, const CL_StringData8 &s)
Insert.
CL_String8 & insert (size_type pos, const CL_StringData8 &s, size_type pos1, size_type length)
Insert.
CL_String8 & insert (size_type pos, const char *s)
Insert.
CL_String8 & insert (size_type pos, const char *s, size_type s_length)
Insert.
CL_String8 & insert (size_type pos, size_type n, char c)
Insert.
size_type length () const
Length.
size_type max_size () const
Max size.
operator CL_StringRef8 () const
std::string
operator std::string () const
std::string
CL_String8 & operator+= (const CL_StringData8 &s)
CL_String8 & operator+= (const wchar_t *c_str)
CL_String8 & operator+= (const char *c_str)
CL_String8 & operator+= (char c)
CL_String8 & operator= (const CL_String8 &source)
CL_String8 & operator= (const CL_StringData8 &source)
CL_String8 & operator= (const char *c_str)
CL_String8 & operator= (const wchar_t *c_str)
const char & operator[] (size_type n) const
char & operator[] (size_type n)
void push_back (char c)
Push back.
CL_String8 & replace (iterator first, iterator last, const CL_StringData8 &s)
Replace.
CL_String8 & replace (iterator first, iterator last, const char *s)
Replace.
CL_String8 & replace (size_type pos, size_type n, const char *s, size_type n1)
Replace.
CL_String8 & replace (iterator first, iterator last, size_type n, char c)
Replace.
CL_String8 & replace (iterator first, iterator last, const char *s, size_type n)
Replace.
CL_String8 & replace (size_type pos, size_type n, size_type n1, char c)
Replace.
CL_String8 & replace (size_type pos, size_type n, const CL_StringData8 &s, size_type pos1, size_type n1)
Replace.
CL_String8 & replace (size_type pos, size_type n, const CL_StringData8 &s)
Replace.
CL_String8 & replace (size_type pos, size_type n, const char *s)
Replace.
void reserve (size_type size)
Reserve.
void resize (size_type n)
Resize.
void resize (size_type n, char c)
Resize.
size_type rfind (const char *s, size_type pos, size_type n) const
Rfind.
size_type rfind (const CL_StringData8 &s, size_type pos=npos) const
Rfind.
size_type rfind (const char *s, size_type pos=npos) const
Rfind.
size_type rfind (char c, size_type pos=npos) const
Rfind.
size_type size () const
Size.
CL_StringRef8 substr (size_type pos=0, size_type n=npos) const
Substr.
size_type utf8_length () const
Static Public Attributes
static const size_type npos
Protected Attributes
size_type data_length
char * data_ptr
Detailed Description
String container template.
Basic string container. Extends StringData with operations that work on string data.
Member Typedef Documentation
typedef char CL_StringData8::char_type [inherited]
typedef const char* CL_StringData8::const_iterator [inherited]
typedef char* CL_StringData8::iterator [inherited]
typedef unsigned int CL_StringData8::size_type [inherited]
Constructor & Destructor Documentation
CL_String8::CL_String8 ()
CL_String8::CL_String8 (const std::string & source)
Constructs a StringContainer.
Parameters:
source = Std String
CL_String8::CL_String8 (const CL_String8 & source)
Constructs a StringContainer.
Parameters:
source = String Container
CL_String8::CL_String8 (const CL_StringData8 & source)
Constructs a StringContainer.
CL_String8::CL_String8 (const char * c_str)
Constructs a StringContainer.
Parameters:
c_str = char
CL_String8::CL_String8 (const char * c_str, size_type length)
Constructs a StringContainer.
Parameters:
c_str = char
length = size_type
CL_String8::CL_String8 (const wchar_t * wc_str)
Constructs a StringContainer.
Parameters:
wc_str = wchar_t
CL_String8::CL_String8 (const wchar_t * wc_str, size_type length)
Constructs a StringContainer.
Parameters:
wc_str = wchar_t
length = size_type
CL_String8::CL_String8 (size_type n, char c)
Constructs a StringContainer.
Parameters:
n = size_type
c = Char Type
CL_String8::~CL_String8 ()
Member Function Documentation
CL_String8& CL_String8::append (const CL_StringData8 & s)
Append.
Parameters:
s = String Data
Returns:
String Container
CL_String8& CL_String8::append (const CL_StringData8 & s, size_type pos, size_type n)
Append.
Parameters:
s = String Data
pos = size_type
n = size_type
Returns:
String Container
CL_String8& CL_String8::append (const char * s)
CL_String8& CL_String8::append (const char * s, size_type n)
Append.
Parameters:
s = char
n = size_type
Returns:
String Container
CL_String8& CL_String8::append (const wchar_t * s)
Append.
Parameters:
s = wchar_t
Returns:
String Container
CL_String8& CL_String8::append (const wchar_t * s, size_type n)
Append.
Parameters:
s = wchar_t
n = size_type
Returns:
String Container
CL_String8& CL_String8::append (size_type n, char c)
Append.
Parameters:
n = size_type
c = Char Type
Returns:
String Container
CL_String8& CL_String8::assign (const char * s, size_type n)
Assign.
Parameters:
s = String data
n = size_type
Returns:
String Container
CL_String8& CL_String8::assign (const CL_StringData8 & s)
CL_String8& CL_String8::assign (const CL_StringData8 & s, size_type pos, size_type n)
Assign.
Parameters:
s = String Data
pos = size_type
n = size_type
Returns:
String Container
CL_String8& CL_String8::assign (const char * s)
Assign.
Parameters:
s = Char Type
Returns:
String Container
CL_String8& CL_String8::assign (size_type n, char c)
Assign.
Parameters:
n = size_type
c = Char Type
Returns:
String Container
iterator CL_StringData8::begin () [inline, inherited]
Begin.
Returns:
iterator
Referenced by erase(), and insert().
const_iterator CL_StringData8::begin () const [inline, inherited]
Begin.
Returns:
const_iterator
const char* CL_String8::c_str () const
Referenced by std::hash< CL_String >::operator()().
size_type CL_String8::capacity () const [inline]
Capacity.
Returns:
size_type
void CL_String8::clear ()
Clear.
int CL_StringData8::compare (const CL_StringData8 & s) const [inherited]
Compare.
Parameters:
s = String Data
Returns:
int
int CL_StringData8::compare (size_type pos, size_type n, const CL_StringData8 & s) const [inherited]
Compare.
Parameters:
pos = size_type
n = size_type
s = String Data
Returns:
int
int CL_StringData8::compare (const char * s) const [inherited]
Compare.
Parameters:
s = Char Type
Returns:
int
int CL_StringData8::compare (size_type pos, size_type n, const char * s, size_type len = npos) const [inherited]
Compare.
Parameters:
pos = size_type
n = size_type
s = Char Type
len = size_type
Returns:
int
int CL_StringData8::compare (size_type pos, size_type n, const CL_StringData8 & s, size_type pos1, size_type n1) const [inherited]
Compare.
Parameters:
pos = size_type
n = size_type
s = String Data
pos1 = size_type
n1 = size_type
Returns:
int
size_type CL_String8::copy (char * buf, size_type n, size_type pos = 0) const
Copy.
Parameters:
buf = Char Type
n = size_type
pos = size_type
Returns:
size_type
const char* CL_StringData8::data () const [inline, inherited]
Referenced by insert().
char* CL_StringData8::data () [inline, inherited]
Data.
Returns:
Char Type
bool CL_StringData8::empty () const [inline, inherited]
Empty.
Returns:
bool
iterator CL_StringData8::end () [inline, inherited]
End.
Returns:
iterator
Referenced by erase().
const_iterator CL_StringData8::end () const [inline, inherited]
End.
Returns:
const_iterator
iterator CL_String8::erase (iterator p) [inline]
Erase.
Parameters:
p = iterator
Returns:
iterator
References CL_StringData8::end().
iterator CL_String8::erase (iterator first, iterator last) [inline]
Erase.
Parameters:
first = iterator
last = iterator
Returns:
iterator
References CL_StringData8::begin(), and CL_StringData8::end().
CL_String8& CL_String8::erase (size_type pos = 0, size_type n = CL_StringData8::npos)
Erase.
Parameters:
pos = size_type
n = size_type
Returns:
String Container
size_type CL_StringData8::find (const char * s, size_type pos = 0) const [inherited]
Find.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::find (char c, size_type pos = 0) const [inherited]
Find.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::find (const CL_StringData8 & s, size_type pos = 0) const [inherited]
Find.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData8::find (const char * s, size_type pos, size_type n) const [inherited]
Find.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData8::find_first_not_of (const CL_StringData8 & s, size_type pos = 0) const [inherited]
Find first not of.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_first_not_of (const char * s, size_type pos, size_type n) const [inherited]
Find first not of.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData8::find_first_not_of (const char * s, size_type pos = 0) const [inherited]
Find first not of.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_first_not_of (char c, size_type pos = 0) const [inherited]
Find first not of.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_first_of (const CL_StringData8 & s, size_type pos = 0) const [inherited]
Find first of.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_first_of (const char * s, size_type pos, size_type n) const [inherited]
Find first of.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData8::find_first_of (const char * s, size_type pos = 0) const [inherited]
Find first of.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_first_of (char c, size_type pos = 0) const [inherited]
Find first of.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_last_not_of (const CL_StringData8 & s, size_type pos = npos) const [inherited]
Find last not of.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_last_not_of (const char * s, size_type pos = npos) const [inherited]
Find last not of.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_last_not_of (char c, size_type pos = npos) const [inherited]
Find last not of.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_last_not_of (const char * s, size_type pos, size_type n) const [inherited]
Find last not of.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData8::find_last_of (const char * s, size_type pos, size_type n) const [inherited]
Find last of.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData8::find_last_of (const CL_StringData8 & s, size_type pos = npos) const [inherited]
Find last of.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_last_of (const char * s, size_type pos = npos) const [inherited]
Find last of.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::find_last_of (char c, size_type pos = npos) const [inherited]
Find last of.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
CL_String8& CL_String8::insert (size_type pos, const CL_StringData8 & s)
Insert.
Parameters:
pos = size_type
s = String Data
Returns:
String Container
CL_String8& CL_String8::insert (size_type pos, const CL_StringData8 & s, size_type pos1, size_type length)
Insert.
Parameters:
pos = size_type
s = String Data
pos1 = size_type
length = size_type
Returns:
String Container
CL_String8& CL_String8::insert (size_type pos, const char * s)
Insert.
Parameters:
pos = size_type
s = Char Type
Returns:
String Container
CL_String8& CL_String8::insert (size_type pos, const char * s, size_type s_length)
Insert.
Parameters:
pos = size_type
s = Char Type
s_length = size_type
Returns:
String Container
CL_String8& CL_String8::insert (size_type pos, size_type n, char c)
Insert.
Parameters:
pos = size_type
n = size_type
c = Char Type
Returns:
String Container
iterator CL_String8::insert (iterator pos, const char & item) [inline]
Insert.
Parameters:
pos = iterator
item = Char Type
Returns:
iterator
References CL_StringData8::begin(), CL_StringData8::data(), and CL_StringData8::length().
void CL_String8::insert (iterator pos, size_type num_copies, const char & item)
Insert.
Parameters:
pos = iterator
num_copies = size_type
item = Char Type
size_type CL_StringData8::length () const [inline, inherited]
Length.
Returns:
size_type
Referenced by insert().
size_type CL_String8::max_size () const [inline]
Max size.
Returns:
size_type
CL_String8::operator CL_StringRef8 () const
std::string
Returns:
operator
Reimplemented from CL_StringData8.
CL_StringData8::operator std::string () const [inherited]
std::string
Returns:
operator
CL_String8& CL_String8::operator+= (char c)
CL_String8& CL_String8::operator+= (const CL_StringData8 & s)
CL_String8& CL_String8::operator+= (const char * c_str)
CL_String8& CL_String8::operator+= (const wchar_t * c_str)
CL_String8& CL_String8::operator= (const CL_String8 & source)
CL_String8& CL_String8::operator= (const char * c_str)
CL_String8& CL_String8::operator= (const CL_StringData8 & source)
CL_String8& CL_String8::operator= (const wchar_t * c_str)
char& CL_StringData8::operator[] (size_type n) [inline, inherited]
const char& CL_StringData8::operator[] (size_type n) const [inline, inherited]
void CL_String8::push_back (char c)
Push back.
Parameters:
c = Char Type
CL_String8& CL_String8::replace (iterator first, iterator last, const char * s)
Replace.
Parameters:
first = iterator
last = iterator
s = Char Type
Returns:
String Container
CL_String8& CL_String8::replace (size_type pos, size_type n, const char * s)
Replace.
Parameters:
pos = size_type
n = size_type
s = Char Type
Returns:
String Container
CL_String8& CL_String8::replace (size_type pos, size_type n, const CL_StringData8 & s, size_type pos1, size_type n1)
Replace.
Parameters:
pos = size_type
n = size_type
s = String Data
pos1 = size_type
n1 = size_type
Returns:
String Container
CL_String8& CL_String8::replace (iterator first, iterator last, const char * s, size_type n)
Replace.
Parameters:
first = iterator
last = iterator
s = Char Type
n = size_type
Returns:
String Container
CL_String8& CL_String8::replace (size_type pos, size_type n, size_type n1, char c)
Replace.
Parameters:
pos = size_type
n = size_type
n1 = size_type
c = Char Type
Returns:
String Container
CL_String8& CL_String8::replace (size_type pos, size_type n, const CL_StringData8 & s)
Replace.
Parameters:
pos = size_type
n = size_type
s = String Data
Returns:
String Container
CL_String8& CL_String8::replace (iterator first, iterator last, const CL_StringData8 & s)
Replace.
Parameters:
first = iterator
last = iterator
s = String Data
Returns:
String Container
CL_String8& CL_String8::replace (iterator first, iterator last, size_type n, char c)
Replace.
Parameters:
first = iterator
last = iterator
n = size_type
c = Char Type
Returns:
String Container
CL_String8& CL_String8::replace (size_type pos, size_type n, const char * s, size_type n1)
Replace.
Parameters:
pos = size_type
n = size_type
s = Char Type
n1 = size_type
Returns:
String Container
void CL_String8::reserve (size_type size)
Reserve.
Parameters:
size = size_type
void CL_String8::resize (size_type n, char c)
Resize.
Parameters:
n = size_type
c = Char Type
void CL_String8::resize (size_type n)
Resize.
Parameters:
n = size_type
size_type CL_StringData8::rfind (char c, size_type pos = npos) const [inherited]
Rfind.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::rfind (const CL_StringData8 & s, size_type pos = npos) const [inherited]
Rfind.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData8::rfind (const char * s, size_type pos, size_type n) const [inherited]
Rfind.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData8::rfind (const char * s, size_type pos = npos) const [inherited]
Rfind.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData8::size () const [inline, inherited]
Size.
Returns:
size_type
CL_StringRef8 CL_StringData8::substr (size_type pos = 0, size_type n = npos) const [inherited]
Substr.
Parameters:
pos = size_type
n = size_type
Returns:
Reference Class
size_type CL_StringData8::utf8_length () const [inherited]
Member Data Documentation
size_type CL_StringData8::data_length [mutable, protected, inherited]
char* CL_StringData8::data_ptr [mutable, protected, inherited]
const size_type CL_StringData8::npos [static, inherited]
The documentation for this class was generated from the following file:
string8.h