ClanLib: CL_NetGameEvent Class Reference
CL_NetGameEvent Class Reference
[clanNetwork NetGame]
CL_NetGameEvent.
#include <event.h>
Public Member Functions
CL_NetGameEvent (const CL_String &name)
Constructs a NetGameEvent.
CL_NetGameEvent (const CL_String &name, const CL_NetGameEventValue &arg1)
Constructs a NetGameEvent.
CL_NetGameEvent (const CL_String &name, const CL_NetGameEventValue &arg1, const CL_NetGameEventValue &arg2, const CL_NetGameEventValue &arg3)
Constructs a NetGameEvent.
CL_NetGameEvent (const CL_String &name, const CL_NetGameEventValue &arg1, const CL_NetGameEventValue &arg2, const CL_NetGameEventValue &arg3, const CL_NetGameEventValue &arg4)
Constructs a NetGameEvent.
CL_NetGameEvent (const CL_String &name, const CL_NetGameEventValue &arg1, const CL_NetGameEventValue &arg2)
Constructs a NetGameEvent.
CL_NetGameEvent (const CL_String &name, const CL_NetGameEventValue &arg1, const CL_NetGameEventValue &arg2, const CL_NetGameEventValue &arg3, const CL_NetGameEventValue &arg4, const CL_NetGameEventValue &arg5)
Constructs a NetGameEvent.
void add_argument (const CL_NetGameEventValue &value)
Add argument.
CL_NetGameEventValue get_argument (unsigned int index) const
Get argument.
unsigned int get_argument_count () const
CL_String get_name () const
Get Name.
CL_String to_string () const
To string.
Detailed Description
CL_NetGameEvent.
Constructor & Destructor Documentation
CL_NetGameEvent::CL_NetGameEvent (const CL_String & name)
Constructs a NetGameEvent.
Parameters:
name = String
CL_NetGameEvent::CL_NetGameEvent (const CL_String & name, const CL_NetGameEventValue & arg1)
Constructs a NetGameEvent.
Parameters:
name = String
arg1 = Net Game Event Value
CL_NetGameEvent::CL_NetGameEvent (const CL_String & name, const CL_NetGameEventValue & arg1, const CL_NetGameEventValue & arg2)
Constructs a NetGameEvent.
Parameters:
name = String
arg1 = Net Game Event Value
arg2 = Net Game Event Value
CL_NetGameEvent::CL_NetGameEvent (const CL_String & name, const CL_NetGameEventValue & arg1, const CL_NetGameEventValue & arg2, const CL_NetGameEventValue & arg3)
Constructs a NetGameEvent.
Parameters:
name = String
arg1 = Net Game Event Value
arg2 = Net Game Event Value
arg3 = Net Game Event Value
CL_NetGameEvent::CL_NetGameEvent (const CL_String & name, const CL_NetGameEventValue & arg1, const CL_NetGameEventValue & arg2, const CL_NetGameEventValue & arg3, const CL_NetGameEventValue & arg4)
Constructs a NetGameEvent.
Parameters:
name = String
arg1 = Net Game Event Value
arg2 = Net Game Event Value
arg3 = Net Game Event Value
arg4 = Net Game Event Value
CL_NetGameEvent::CL_NetGameEvent (const CL_String & name, const CL_NetGameEventValue & arg1, const CL_NetGameEventValue & arg2, const CL_NetGameEventValue & arg3, const CL_NetGameEventValue & arg4, const CL_NetGameEventValue & arg5)
Constructs a NetGameEvent.
Parameters:
name = String
arg1 = Net Game Event Value
arg2 = Net Game Event Value
arg3 = Net Game Event Value
arg4 = Net Game Event Value
arg5 = Net Game Event Value
Member Function Documentation
void CL_NetGameEvent::add_argument (const CL_NetGameEventValue & value)
Add argument.
Parameters:
value = Net Game Event Value
CL_NetGameEventValue CL_NetGameEvent::get_argument (unsigned int index) const
Get argument.
Parameters:
index = value
Returns:
Net Game Event Value
unsigned int CL_NetGameEvent::get_argument_count () const
CL_String CL_NetGameEvent::get_name () const [inline]
Get Name.
Returns:
name
Referenced by CL_NetGameEventDispatcher_v3< ContextParam1, ContextParam2, ContextParam3 >::dispatch(), CL_NetGameEventDispatcher_v2< ContextParam1, ContextParam2 >::dispatch(), CL_NetGameEventDispatcher_v1< ContextParam >::dispatch(), and CL_NetGameEventDispatcher_v0::dispatch().
CL_String CL_NetGameEvent::to_string () const
To string.
Returns:
String
The documentation for this class was generated from the following file:
Network/NetGame/event.h