ClanLib: CL_DBValue Class Reference
CL_DBValue Class Reference
#include <db_value.h>
Public Member Functions
CL_DBValue ()
CL_DBValue (const CL_DBReader &db_reader, int column_index)
CL_DBValue (const CL_DBReader &db_reader, const CL_StringRef &column_name)
operator bool () const
operator CL_DataBuffer () const
operator CL_DateTime () const
operator CL_String () const
operator double () const
operator int () const
CL_DataBuffer to_binary () const
bool to_boolean () const
CL_DateTime to_datetime () const
double to_double () const
int to_integer () const
CL_String to_string () const
Constructor & Destructor Documentation
CL_DBValue::CL_DBValue ()
CL_DBValue::CL_DBValue (const CL_DBReader & db_reader, int column_index)
CL_DBValue::CL_DBValue (const CL_DBReader & db_reader, const CL_StringRef & column_name)
Member Function Documentation
CL_DBValue::operator bool () const [inline]
References to_boolean().
CL_DBValue::operator CL_DataBuffer () const [inline]
References to_binary().
CL_DBValue::operator CL_DateTime () const [inline]
References to_datetime().
CL_DBValue::operator CL_String () const [inline]
References to_string().
CL_DBValue::operator double () const [inline]
References to_double().
CL_DBValue::operator int () const [inline]
References to_integer().
CL_DataBuffer CL_DBValue::to_binary () const
Referenced by operator CL_DataBuffer().
bool CL_DBValue::to_boolean () const
Referenced by operator bool().
CL_DateTime CL_DBValue::to_datetime () const
Referenced by operator CL_DateTime().
double CL_DBValue::to_double () const
Referenced by operator double().
int CL_DBValue::to_integer () const
Referenced by operator int().
CL_String CL_DBValue::to_string () const
Referenced by operator CL_String().
The documentation for this class was generated from the following file:
db_value.h