ClanLib: CL_StringFormat Class Reference
CL_StringFormat Class Reference
[clanCore Text]
String formatting class.
#include <string_format.h>
Classes
struct ArgPosition
Public Member Functions
Construction
CL_StringFormat (const CL_StringRef &format_string)
Constructs a TempStringFormat.
~CL_StringFormat ()
Attributes
const CL_String & get_result () const
Operations
void set_arg (int index, const CL_StringRef &text)
Set arg.
void set_arg (int index, int value, int min_length=0)
Set arg.
void set_arg (int index, unsigned int value, int min_length=0)
Set arg.
void set_arg (int index, long unsigned int value, int min_length=0)
Set arg.
void set_arg (int index, long long value, int min_length=0)
Set arg.
void set_arg (int index, unsigned long long value, int min_length=0)
Set arg.
void set_arg (int index, float value)
Set arg.
void set_arg (int index, double value)
Set arg.
Detailed Description
String formatting class.
Constructor & Destructor Documentation
CL_StringFormat::CL_StringFormat (const CL_StringRef & format_string)
Constructs a TempStringFormat.
Parameters:
format_string = String Ref
CL_StringFormat::~CL_StringFormat ()
Member Function Documentation
const CL_String& CL_StringFormat::get_result () const
Referenced by cl_format(), cl_log_event(), CL_Console::write(), and CL_Console::write_line().
void CL_StringFormat::set_arg (int index, double value)
Set arg.
Parameters:
index = value
value = value
void CL_StringFormat::set_arg (int index, float value)
Set arg.
Parameters:
index = value
value = value
void CL_StringFormat::set_arg (int index, unsigned long long value, int min_length = 0)
Set arg.
Parameters:
index = value
value = value
min_length = value
void CL_StringFormat::set_arg (int index, long long value, int min_length = 0)
Set arg.
Parameters:
index = value
value = value
min_length = value
void CL_StringFormat::set_arg (int index, long unsigned int value, int min_length = 0)
Set arg.
Parameters:
index = value
value = value
min_length = value
void CL_StringFormat::set_arg (int index, unsigned int value, int min_length = 0)
Set arg.
Parameters:
index = value
value = value
min_length = value
void CL_StringFormat::set_arg (int index, int value, int min_length = 0)
Set arg.
Parameters:
index = value
value = value
min_length = value
void CL_StringFormat::set_arg (int index, const CL_StringRef & text)
Set arg.
Parameters:
index = value
text = String Ref
Referenced by cl_format(), cl_log_event(), CL_Console::write(), and CL_Console::write_line().
The documentation for this class was generated from the following file:
string_format.h