ClanLib: CL_RunnableMember_v2< C, P1, P2 > Class Template Reference
CL_RunnableMember_v2< C, P1, P2 > Class Template Reference
[clanCore System]
#include <runnable.h>
Public Member Functions
Operations
virtual void run ()
Static Public Member Functions
Operations
static void set_thread_name (const char *name)
Sets the name (displayed in debuggers) of the calling thread.
Construction
typedef void(C::* PtrMemberFunc)(P1 p1, P2 p2)
CL_RunnableMember_v2 (C *instance, PtrMemberFunc func, P1 p1, P2 p2)
Detailed Description
template<class C, class P1, class P2>
class CL_RunnableMember_v2< C, P1, P2 >
(Internal ClanLib Class)
Member Typedef Documentation
template<class C, class P1, class P2> typedef void(C::* CL_RunnableMember_v2< C, P1, P2 >::PtrMemberFunc)(P1 p1, P2 p2)
Constructor & Destructor Documentation
template<class C, class P1, class P2> CL_RunnableMember_v2< C, P1, P2 >::CL_RunnableMember_v2 (C * instance, PtrMemberFunc func, P1 p1, P2 p2) [inline]
Member Function Documentation
template<class C, class P1, class P2> virtual void CL_RunnableMember_v2< C, P1, P2 >::run () [inline, virtual]
Implements CL_Runnable.
References CL_Runnable::set_thread_name().
static void CL_Runnable::set_thread_name (const char * name) [static, inherited]
Sets the name (displayed in debuggers) of the calling thread.
Currently this only works with the Visual Studio compiler and debugger.
Referenced by CL_RunnableMember_v5< C, P1, P2, P3, P4, P5 >::run(), CL_RunnableMember_v4< C, P1, P2, P3, P4 >::run(), CL_RunnableMember_v3< C, P1, P2, P3 >::run(), CL_RunnableMember_v2< C, P1, P2 >::run(), CL_RunnableMember_v1< C, P1 >::run(), and CL_RunnableMember_v0< C >::run().
The documentation for this class was generated from the following file:
runnable.h