ClanLib: CL_Super_0< RetVal > Class Template Reference
CL_Super_0< RetVal > Class Template Reference
[clanCore Signals]
#include <virtual_function_0.h>
Public Member Functions
RetVal invoke ()
bool is_invokable () const
bool is_null () const
Public Attributes
std::vector< CL_SharedPtr
< CL_SlotCallback >
>::reverse_iterator it_end
std::vector< CL_SharedPtr
< CL_SlotCallback >
>::reverse_iterator it_super
Detailed Description
template<typename RetVal>
class CL_Super_0< RetVal >
(Internal ClanLib Class)
Member Function Documentation
template<typename RetVal> RetVal CL_Super_0< RetVal >::invoke () [inline]
References CL_Super_0< RetVal >::it_end, and CL_Super_0< RetVal >::it_super.
Referenced by CL_VirtualFunction_0< RetVal >::invoke().
template<typename RetVal> bool CL_Super_0< RetVal >::is_invokable () const [inline]
References CL_Super_0< RetVal >::is_null().
template<typename RetVal> bool CL_Super_0< RetVal >::is_null () const [inline]
References CL_Super_0< RetVal >::it_end, and CL_Super_0< RetVal >::it_super.
Referenced by CL_Super_0< RetVal >::is_invokable().
Member Data Documentation
template<typename RetVal> std::vector< CL_SharedPtr<CL_SlotCallback> >::reverse_iterator CL_Super_0< RetVal >::it_end
Referenced by CL_VirtualFunction_0< RetVal >::invoke(), CL_Super_0< RetVal >::invoke(), and CL_Super_0< RetVal >::is_null().
template<typename RetVal> std::vector< CL_SharedPtr<CL_SlotCallback> >::reverse_iterator CL_Super_0< RetVal >::it_super
Referenced by CL_VirtualFunction_0< RetVal >::invoke(), CL_Super_0< RetVal >::invoke(), and CL_Super_0< RetVal >::is_null().
The documentation for this class was generated from the following file:
virtual_function_0.h