ClanLib: CL_Runnable Class Reference
CL_Runnable Class Reference
[clanCore System]
Thread runnable object.
#include <runnable.h>
Public Member Functions
Construction
CL_Runnable ()
virtual ~CL_Runnable ()
Operations
virtual void run ()=0
static void set_thread_name (const char *name)
Sets the name (displayed in debuggers) of the calling thread.
Detailed Description
Thread runnable object.
Constructor & Destructor Documentation
CL_Runnable::CL_Runnable ()
virtual CL_Runnable::~CL_Runnable () [virtual]
Member Function Documentation
virtual void CL_Runnable::run () [pure virtual]
Implemented in CL_RunnableMember_v0< C >, CL_RunnableMember_v1< C, P1 >, CL_RunnableMember_v2< C, P1, P2 >, CL_RunnableMember_v3< C, P1, P2, P3 >, CL_RunnableMember_v4< C, P1, P2, P3, P4 >, and CL_RunnableMember_v5< C, P1, P2, P3, P4, P5 >.
static void CL_Runnable::set_thread_name (const char * name) [static]
Sets the name (displayed in debuggers) of the calling thread.
Currently this only works with the Visual Studio compiler and debugger.
Referenced by CL_RunnableMember_v5< C, P1, P2, P3, P4, P5 >::run(), CL_RunnableMember_v4< C, P1, P2, P3, P4 >::run(), CL_RunnableMember_v3< C, P1, P2, P3 >::run(), CL_RunnableMember_v2< C, P1, P2 >::run(), CL_RunnableMember_v1< C, P1 >::run(), and CL_RunnableMember_v0< C >::run().
The documentation for this class was generated from the following file:
runnable.h