ClanLib: CL_StringData16 Class Reference
CL_StringData16 Class Reference
[clanCore Text]
String data class for 16 bit data.
#include <string_data16.h>
Public Types
typedef wchar_t char_type
typedef const wchar_t * const_iterator
typedef wchar_t * iterator
typedef unsigned int size_type
Public Member Functions
CL_StringData16 ()
CL_StringData16 (const wchar_t *ptr, size_type length)
Constructs a StringData8.
const_iterator begin () const
Begin.
iterator begin ()
Begin.
int compare (const CL_StringData16 &s) const
Compare.
int compare (size_type pos, size_type n, const CL_StringData16 &s) const
Compare.
int compare (size_type pos, size_type n, const CL_StringData16 &s, size_type pos1, size_type n1) const
Compare.
int compare (const wchar_t *s) const
Compare.
int compare (size_type pos, size_type n, const wchar_t *s, size_type len=npos) const
Compare.
const wchar_t * data () const
wchar_t * data ()
Data.
bool empty () const
Empty.
iterator end ()
End.
const_iterator end () const
End.
size_type find (const CL_StringData16 &s, size_type pos=0) const
Find.
size_type find (const wchar_t *s, size_type pos, size_type n) const
Find.
size_type find (const wchar_t *s, size_type pos=0) const
Find.
size_type find (wchar_t c, size_type pos=0) const
Find.
size_type find_first_not_of (wchar_t c, size_type pos=0) const
Find first not of.
size_type find_first_not_of (const CL_StringData16 &s, size_type pos=0) const
Find first not of.
size_type find_first_not_of (const wchar_t *s, size_type pos, size_type n) const
Find first not of.
size_type find_first_not_of (const wchar_t *s, size_type pos=0) const
Find first not of.
size_type find_first_of (const CL_StringData16 &s, size_type pos=0) const
Find first of.
size_type find_first_of (const wchar_t *s, size_type pos, size_type n) const
Find first of.
size_type find_first_of (const wchar_t *s, size_type pos=0) const
Find first of.
size_type find_first_of (wchar_t c, size_type pos=0) const
Find first of.
size_type find_last_not_of (const CL_StringData16 &s, size_type pos=npos) const
Find last not of.
size_type find_last_not_of (const wchar_t *s, size_type pos=npos) const
Find last not of.
size_type find_last_not_of (const wchar_t *s, size_type pos, size_type n) const
Find last not of.
size_type find_last_not_of (wchar_t c, size_type pos=npos) const
Find last not of.
size_type find_last_of (const CL_StringData16 &s, size_type pos=npos) const
Find last of.
size_type find_last_of (const wchar_t *s, size_type pos=npos) const
Find last of.
size_type find_last_of (wchar_t c, size_type pos=npos) const
Find last of.
size_type find_last_of (const wchar_t *s, size_type pos, size_type n) const
Find last of.
size_type length () const
Length.
operator CL_StringRef16 () const
Convert object to a string reference.
operator std::wstring () const
std::wstring
const wchar_t & operator[] (size_type n) const
wchar_t & operator[] (size_type n)
size_type rfind (const wchar_t *s, size_type pos, size_type n) const
Rfind.
size_type rfind (const CL_StringData16 &s, size_type pos=npos) const
Rfind.
size_type rfind (const wchar_t *s, size_type pos=npos) const
Rfind.
size_type rfind (wchar_t c, size_type pos=npos) const
Rfind.
size_type size () const
Size.
CL_StringRef16 substr (size_type pos=0, size_type n=npos) const
Substr.
Static Public Attributes
static const size_type npos
Protected Attributes
size_type data_length
wchar_t * data_ptr
Detailed Description
String data class for 16 bit data.
Member Typedef Documentation
typedef wchar_t CL_StringData16::char_type
typedef const wchar_t* CL_StringData16::const_iterator
typedef wchar_t* CL_StringData16::iterator
typedef unsigned int CL_StringData16::size_type
Constructor & Destructor Documentation
CL_StringData16::CL_StringData16 ()
CL_StringData16::CL_StringData16 (const wchar_t * ptr, size_type length)
Constructs a StringData8.
Parameters:
ptr = Char Type
length = size_type
Member Function Documentation
iterator CL_StringData16::begin () [inline]
Begin.
Returns:
iterator
Referenced by CL_String16::erase(), and CL_String16::insert().
const_iterator CL_StringData16::begin () const [inline]
Begin.
Returns:
const_iterator
int CL_StringData16::compare (const CL_StringData16 & s) const
Compare.
Parameters:
s = String Data
Returns:
int
int CL_StringData16::compare (size_type pos, size_type n, const CL_StringData16 & s) const
Compare.
Parameters:
pos = size_type
n = size_type
s = String Data
Returns:
int
int CL_StringData16::compare (size_type pos, size_type n, const CL_StringData16 & s, size_type pos1, size_type n1) const
Compare.
Parameters:
pos = size_type
n = size_type
s = String Data
pos1 = size_type
n1 = size_type
Returns:
int
int CL_StringData16::compare (const wchar_t * s) const
Compare.
Parameters:
s = Char Type
Returns:
int
int CL_StringData16::compare (size_type pos, size_type n, const wchar_t * s, size_type len = npos) const
Compare.
Parameters:
pos = size_type
n = size_type
s = Char Type
len = size_type
Returns:
int
wchar_t* CL_StringData16::data () [inline]
Data.
Returns:
Char Type
const wchar_t* CL_StringData16::data () const [inline]
Referenced by CL_String16::insert().
bool CL_StringData16::empty () const [inline]
Empty.
Returns:
bool
const_iterator CL_StringData16::end () const [inline]
End.
Returns:
const_iterator
iterator CL_StringData16::end () [inline]
End.
Returns:
iterator
Referenced by CL_String16::erase().
size_type CL_StringData16::find (const wchar_t * s, size_type pos = 0) const
Find.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find (wchar_t c, size_type pos = 0) const
Find.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find (const CL_StringData16 & s, size_type pos = 0) const
Find.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData16::find (const wchar_t * s, size_type pos, size_type n) const
Find.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData16::find_first_not_of (const CL_StringData16 & s, size_type pos = 0) const
Find first not of.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_first_not_of (const wchar_t * s, size_type pos, size_type n) const
Find first not of.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData16::find_first_not_of (const wchar_t * s, size_type pos = 0) const
Find first not of.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_first_not_of (wchar_t c, size_type pos = 0) const
Find first not of.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_first_of (const CL_StringData16 & s, size_type pos = 0) const
Find first of.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_first_of (const wchar_t * s, size_type pos, size_type n) const
Find first of.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData16::find_first_of (const wchar_t * s, size_type pos = 0) const
Find first of.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_first_of (wchar_t c, size_type pos = 0) const
Find first of.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_last_not_of (const CL_StringData16 & s, size_type pos = npos) const
Find last not of.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_last_not_of (wchar_t c, size_type pos = npos) const
Find last not of.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_last_not_of (const wchar_t * s, size_type pos = npos) const
Find last not of.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_last_not_of (const wchar_t * s, size_type pos, size_type n) const
Find last not of.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData16::find_last_of (const wchar_t * s, size_type pos = npos) const
Find last of.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_last_of (wchar_t c, size_type pos = npos) const
Find last of.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::find_last_of (const wchar_t * s, size_type pos, size_type n) const
Find last of.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData16::find_last_of (const CL_StringData16 & s, size_type pos = npos) const
Find last of.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData16::length () const [inline]
Length.
Returns:
size_type
Referenced by CL_String16::insert().
CL_StringData16::operator CL_StringRef16 () const
Convert object to a string reference.
Returns:
operator
Reimplemented in CL_String16.
CL_StringData16::operator std::wstring () const
std::wstring
Returns:
operator
const wchar_t& CL_StringData16::operator[] (size_type n) const [inline]
wchar_t& CL_StringData16::operator[] (size_type n) [inline]
size_type CL_StringData16::rfind (const wchar_t * s, size_type pos, size_type n) const
Rfind.
Parameters:
s = Char Type
pos = size_type
n = size_type
Returns:
size_type
size_type CL_StringData16::rfind (wchar_t c, size_type pos = npos) const
Rfind.
Parameters:
c = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::rfind (const CL_StringData16 & s, size_type pos = npos) const
Rfind.
Parameters:
s = String Data
pos = size_type
Returns:
size_type
size_type CL_StringData16::rfind (const wchar_t * s, size_type pos = npos) const
Rfind.
Parameters:
s = Char Type
pos = size_type
Returns:
size_type
size_type CL_StringData16::size () const [inline]
Size.
Returns:
size_type
CL_StringRef16 CL_StringData16::substr (size_type pos = 0, size_type n = npos) const
Substr.
Parameters:
pos = size_type
n = size_type
Returns:
Reference Class
Member Data Documentation
size_type CL_StringData16::data_length [mutable, protected]
wchar_t* CL_StringData16::data_ptr [mutable, protected]
const size_type CL_StringData16::npos [static]
The documentation for this class was generated from the following file:
string_data16.h