ClanLib: CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 > Class Template Reference
CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 > Class Template Reference
[clanCore Signals]
#include <virtual_function_5.h>
Public Member Functions
RetVal invoke (Param1 param1, Param2 param2, Param3 param3, Param4 param4, Param5 param5)
bool is_invokable () const
bool is_null () const
Public Attributes
std::vector< CL_SharedPtr
< CL_SlotCallback >
>::reverse_iterator it_end
std::vector< CL_SharedPtr
< CL_SlotCallback >
>::reverse_iterator it_super
Detailed Description
template<typename RetVal, class Param1, class Param2, class Param3, class Param4, class Param5>
class CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >
(Internal ClanLib Class)
Member Function Documentation
template<typename RetVal, class Param1, class Param2, class Param3, class Param4, class Param5> RetVal CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::invoke (Param1 param1, Param2 param2, Param3 param3, Param4 param4, Param5 param5) [inline]
References CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::it_end, and CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::it_super.
Referenced by CL_VirtualFunction_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::invoke().
template<typename RetVal, class Param1, class Param2, class Param3, class Param4, class Param5> bool CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::is_invokable () const [inline]
References CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::is_null().
template<typename RetVal, class Param1, class Param2, class Param3, class Param4, class Param5> bool CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::is_null () const [inline]
References CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::it_end, and CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::it_super.
Referenced by CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::is_invokable().
Member Data Documentation
template<typename RetVal, class Param1, class Param2, class Param3, class Param4, class Param5> std::vector< CL_SharedPtr<CL_SlotCallback> >::reverse_iterator CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::it_end
Referenced by CL_VirtualFunction_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::invoke(), CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::invoke(), and CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::is_null().
template<typename RetVal, class Param1, class Param2, class Param3, class Param4, class Param5> std::vector< CL_SharedPtr<CL_SlotCallback> >::reverse_iterator CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::it_super
Referenced by CL_VirtualFunction_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::invoke(), CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::invoke(), and CL_Super_5< RetVal, Param1, Param2, Param3, Param4, Param5 >::is_null().
The documentation for this class was generated from the following file:
virtual_function_5.h