ClanLib: CL_ShaderObjectProvider Class Reference
CL_ShaderObjectProvider Class Reference
[clanDisplay Display]
Shader Object provider.
#include <shader_object_provider.h>
Public Member Functions
Construction
virtual ~CL_ShaderObjectProvider ()
virtual void create (CL_ShaderType type, const CL_StringRef &source)=0
Creates a shader object.
virtual void create (CL_ShaderType type, const std::vector< CL_StringRef > &sources)=0
Create.
virtual void destroy ()=0
Destroys the shadoer object provider.
Attributes
virtual unsigned int get_handle () const =0
Returns the OpenGL shader handle.
virtual bool get_compile_status () const =0
Returns true if compile succeeded.
virtual CL_ShaderType get_shader_type () const =0
Gets the shader type.
virtual CL_String get_info_log () const =0
Get shader object's info log.
virtual CL_String get_shader_source () const =0
Get shader source code.
Operations
virtual void compile ()=0
Compile program.
Detailed Description
Shader Object provider.
Constructor & Destructor Documentation
virtual CL_ShaderObjectProvider::~CL_ShaderObjectProvider () [inline, virtual]
References compile(), create(), destroy(), get_compile_status(), get_handle(), get_info_log(), get_shader_source(), and get_shader_type().
Member Function Documentation
virtual void CL_ShaderObjectProvider::compile () [pure virtual]
Compile program.
Referenced by ~CL_ShaderObjectProvider().
virtual void CL_ShaderObjectProvider::create (CL_ShaderType type, const CL_StringRef & source) [pure virtual]
Creates a shader object.
Referenced by ~CL_ShaderObjectProvider().
virtual void CL_ShaderObjectProvider::create (CL_ShaderType type, const std::vector< CL_StringRef > & sources) [pure virtual]
Create.
Parameters:
type = Shader Type
vector = std
virtual void CL_ShaderObjectProvider::destroy () [pure virtual]
Destroys the shadoer object provider.
Referenced by ~CL_ShaderObjectProvider().
virtual bool CL_ShaderObjectProvider::get_compile_status () const [pure virtual]
Returns true if compile succeeded.
Referenced by ~CL_ShaderObjectProvider().
virtual unsigned int CL_ShaderObjectProvider::get_handle () const [pure virtual]
Returns the OpenGL shader handle.
Referenced by ~CL_ShaderObjectProvider().
virtual CL_String CL_ShaderObjectProvider::get_info_log () const [pure virtual]
Get shader object's info log.
Referenced by ~CL_ShaderObjectProvider().
virtual CL_String CL_ShaderObjectProvider::get_shader_source () const [pure virtual]
Get shader source code.
Referenced by ~CL_ShaderObjectProvider().
virtual CL_ShaderType CL_ShaderObjectProvider::get_shader_type () const [pure virtual]
Gets the shader type.
Referenced by ~CL_ShaderObjectProvider().
The documentation for this class was generated from the following file:
shader_object_provider.h