ClanLib: CL_Console Class Reference
CL_Console Class Reference
[clanCore Text]
Console access helper class.
#include <console.h>
Static Public Member Functions
Operations
static void write (const CL_StringRef &text)
Writes text to the console window.
template<class Arg1 >
static void write (const CL_StringRef &format, Arg1 arg1)
Write.
template<class Arg1 , class Arg2 >
static void write (const CL_StringRef &format, Arg1 arg1, Arg2 arg2)
Write.
template<class Arg1 , class Arg2 , class Arg3 >
static void write (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3)
Write.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 >
static void write (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4)
Write.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 >
static void write (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5)
Write.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 >
static void write (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6)
Write.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 >
static void write (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7)
Write.
static void write_line (const CL_StringRef &text)
Writes text to the console window and then advances to a new line.
template<class Arg1 >
static void write_line (const CL_StringRef &format, Arg1 arg1)
Write line.
template<class Arg1 , class Arg2 >
static void write_line (const CL_StringRef &format, Arg1 arg1, Arg2 arg2)
Write line.
template<class Arg1 , class Arg2 , class Arg3 >
static void write_line (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3)
Write line.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 >
static void write_line (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4)
Write line.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 >
static void write_line (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5)
Write line.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 >
static void write_line (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6)
Write line.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 >
static void write_line (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7)
Write line.
static void wait_for_key ()
Block until a key is pressed in the console window.
Detailed Description
Console access helper class.
Member Function Documentation
static void CL_Console::wait_for_key () [static]
Block until a key is pressed in the console window.
This function does not do anything on Linux.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 > static void CL_Console::write (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7) [inline, static]
Write.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
arg4 = Arg4
arg5 = Arg5
arg6 = Arg6
arg7 = Arg7
static void CL_Console::write (const CL_StringRef & text) [static]
Writes text to the console window.
Referenced by write().
template<class Arg1 > static void CL_Console::write (const CL_StringRef & format, Arg1 arg1) [inline, static]
Write.
Parameters:
format = String Ref
arg1 = Arg1
template<class Arg1 , class Arg2 , class Arg3 > static void CL_Console::write (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3) [inline, static]
Write.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 > static void CL_Console::write (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4) [inline, static]
Write.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
arg4 = Arg4
References CL_StringFormat::get_result(), CL_StringFormat::set_arg(), and write().
template<class Arg1 , class Arg2 > static void CL_Console::write (const CL_StringRef & format, Arg1 arg1, Arg2 arg2) [inline, static]
Write.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 > static void CL_Console::write (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5) [inline, static]
Write.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
arg4 = Arg4
arg5 = Arg5
References CL_StringFormat::get_result(), CL_StringFormat::set_arg(), and write().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 > static void CL_Console::write (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6) [inline, static]
Write.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
arg4 = Arg4
arg5 = Arg5
arg6 = Arg6
References CL_StringFormat::get_result(), CL_StringFormat::set_arg(), and write().
static void CL_Console::write_line (const CL_StringRef & text) [inline, static]
Writes text to the console window and then advances to a new line.
Referenced by write_line().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 > static void CL_Console::write_line (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7) [inline, static]
Write line.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
arg4 = Arg4
arg5 = Arg5
arg6 = Arg6
arg7 = Arg7
template<class Arg1 , class Arg2 > static void CL_Console::write_line (const CL_StringRef & format, Arg1 arg1, Arg2 arg2) [inline, static]
Write line.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
template<class Arg1 , class Arg2 , class Arg3 > static void CL_Console::write_line (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3) [inline, static]
Write line.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 > static void CL_Console::write_line (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5) [inline, static]
Write line.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
arg4 = Arg4
arg5 = Arg5
References CL_StringFormat::get_result(), CL_StringFormat::set_arg(), and write_line().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 > static void CL_Console::write_line (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6) [inline, static]
Write line.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
arg4 = Arg4
arg5 = Arg5
arg6 = Arg6
References CL_StringFormat::get_result(), CL_StringFormat::set_arg(), and write_line().
template<class Arg1 > static void CL_Console::write_line (const CL_StringRef & format, Arg1 arg1) [inline, static]
Write line.
Parameters:
format = String Ref
arg1 = Arg1
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 > static void CL_Console::write_line (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4) [inline, static]
Write line.
Parameters:
format = String Ref
arg1 = Arg1
arg2 = Arg2
arg3 = Arg3
arg4 = Arg4
References CL_StringFormat::get_result(), CL_StringFormat::set_arg(), and write_line().
The documentation for this class was generated from the following file:
console.h