ClanLib: CL_ProviderType_Register< ProviderClass > Class Template Reference
CL_ProviderType_Register< ProviderClass > Class Template Reference
[clanDisplay Image Providers]
Class template to register a provider type.
#include <provider_type_register.h>
Public Member Functions
Construction
CL_ProviderType_Register (const CL_String &type)
Registers provider type in the CL_ProviderFactory.
Operations
virtual CL_PixelBuffer load (const CL_String &filename, const CL_VirtualDirectory &directory)
Called to load an image with this provider type.
virtual CL_PixelBuffer load (CL_IODevice &file)
virtual void save (CL_PixelBuffer buffer, const CL_String &filename, CL_VirtualDirectory &directory)
Called to save a given PixelBuffer to a file.
virtual void save (CL_PixelBuffer buffer, CL_IODevice &file)
Detailed Description
template<class ProviderClass>
class CL_ProviderType_Register< ProviderClass >
Class template to register a provider type.
Constructor & Destructor Documentation
template<class ProviderClass > CL_ProviderType_Register< ProviderClass >::CL_ProviderType_Register (const CL_String & type) [inline]
Registers provider type in the CL_ProviderFactory.
References CL_ImageProviderType::CL_ImageProviderType(), and CL_ProviderType_Register< ProviderClass >::load().
Member Function Documentation
template<class ProviderClass > virtual CL_PixelBuffer CL_ProviderType_Register< ProviderClass >::load (const CL_String & filename, const CL_VirtualDirectory & directory) [inline, virtual]
Called to load an image with this provider type.
Implements CL_ImageProviderType.
Referenced by CL_ProviderType_Register< ProviderClass >::CL_ProviderType_Register(), CL_ProviderType_Register< ProviderClass >::load(), and CL_ProviderType_Register< ProviderClass >::save().
template<class ProviderClass > virtual CL_PixelBuffer CL_ProviderType_Register< ProviderClass >::load (CL_IODevice & file) [inline, virtual]
Implements CL_ImageProviderType.
References CL_ProviderType_Register< ProviderClass >::load().
template<class ProviderClass > virtual void CL_ProviderType_Register< ProviderClass >::save (CL_PixelBuffer buffer, const CL_String & filename, CL_VirtualDirectory & directory) [inline, virtual]
Called to save a given PixelBuffer to a file.
Implements CL_ImageProviderType.
References CL_ProviderType_Register< ProviderClass >::load().
Referenced by CL_ProviderType_Register< ProviderClass >::save().
template<class ProviderClass > virtual void CL_ProviderType_Register< ProviderClass >::save (CL_PixelBuffer buffer, CL_IODevice & file) [inline, virtual]
Implements CL_ImageProviderType.
References CL_ProviderType_Register< ProviderClass >::save().
The documentation for this class was generated from the following file:
provider_type_register.h