ClanLib: CL_PixelBufferData Class Reference
CL_PixelBufferData Class Reference
[clanSWRender Display]
Frame buffer or texture data for pixel commands.
#include <pixel_buffer_data.h>
Public Member Functions
CL_PixelBufferData ()
Construction.
void set (const CL_PixelBuffer &new_pixelbuffer)
Operations.
Public Attributes
unsigned int * data
CL_PixelBuffer pixelbuffer
Attributes.
CL_Size size
Detailed Description
Frame buffer or texture data for pixel commands.
Constructor & Destructor Documentation
CL_PixelBufferData::CL_PixelBufferData () [inline]
Construction.
Member Function Documentation
void CL_PixelBufferData::set (const CL_PixelBuffer & new_pixelbuffer) [inline]
Operations.
References data, CL_PixelBuffer::get_data(), CL_PixelBuffer::get_size(), CL_PixelBuffer::is_null(), pixelbuffer, and size.
Member Data Documentation
unsigned int* CL_PixelBufferData::data
Referenced by set().
CL_PixelBuffer CL_PixelBufferData::pixelbuffer
Attributes.
Referenced by set().
CL_Size CL_PixelBufferData::size
Referenced by set().
The documentation for this class was generated from the following file:
pixel_buffer_data.h