ClanLib: clanNetwork NetGame
clanNetwork NetGame
Classes
class CL_NetGameClient
CL_NetGameClient.
class CL_NetGameConnection
CL_NetGameConnection.
class CL_NetGameConnectionSite
CL_NetGameConnectionSite.
class CL_NetGameEvent
CL_NetGameEvent.
class CL_NetGameEventDispatcher_v0
CL_NetGameEventDispatcher_v0.
class CL_NetGameEventDispatcher_v1< ContextParam >
CL_NetGameEventDispatcher_v1.
class CL_NetGameEventDispatcher_v2< ContextParam1, ContextParam2 >
CL_NetGameEventDispatcher_v2.
class CL_NetGameEventDispatcher_v3< ContextParam1, ContextParam2, ContextParam3 >
CL_NetGameEventDispatcher_v3.
class CL_NetGameEventValue
CL_NetGameEventValue.
class CL_NetGameServer
CL_NetGameServer.
Functions
bool CL_NetGameEventDispatcher_v0::dispatch (const CL_NetGameEvent &game_event)
Dispatch.
bool CL_NetGameEventDispatcher_v3::dispatch (const CL_NetGameEvent &game_event, ContextParam1 context1, ContextParam2 context2, ContextParam3 context3)
Dispatch.
bool CL_NetGameEventDispatcher_v2::dispatch (const CL_NetGameEvent &game_event, ContextParam1 context1, ContextParam2 context2)
Dispatch.
bool CL_NetGameEventDispatcher_v1::dispatch (const CL_NetGameEvent &game_event, ContextParam context)
Dispatch.
Function Documentation
bool CL_NetGameEventDispatcher_v0::dispatch (const CL_NetGameEvent & game_event) [inline, inherited]
Dispatch.
Parameters:
game_event = Net Game Event
Returns:
bool
References CL_NetGameEvent::get_name().
template<typename ContextParam1 , typename ContextParam2 , typename ContextParam3 > bool CL_NetGameEventDispatcher_v3< ContextParam1, ContextParam2, ContextParam3 >::dispatch (const CL_NetGameEvent & game_event, ContextParam1 context1, ContextParam2 context2, ContextParam3 context3) [inherited]
Dispatch.
Parameters:
game_event = Net Game Event
context1 = Context Param1
context2 = Context Param2
context3 = Context Param3
Returns:
bool
References CL_NetGameEvent::get_name().
template<typename ContextParam1 , typename ContextParam2 > bool CL_NetGameEventDispatcher_v2< ContextParam1, ContextParam2 >::dispatch (const CL_NetGameEvent & game_event, ContextParam1 context1, ContextParam2 context2) [inherited]
Dispatch.
Parameters:
game_event = Net Game Event
context1 = Context Param1
context2 = Context Param2
Returns:
bool
References CL_NetGameEvent::get_name().
template<typename ContextParam > bool CL_NetGameEventDispatcher_v1< ContextParam >::dispatch (const CL_NetGameEvent & game_event, ContextParam context) [inherited]
Dispatch.
Parameters:
game_event = Net Game Event
context = Context Param
Returns:
bool
References CL_NetGameEvent::get_name().