ClanLib: clanCore Text
clanCore Text
Classes
class CL_Console
Console access helper class.
class CL_ConsoleLogger
Console logger.
class CL_FileLogger
File logger.
class CL_Logger
Logger interface.
class CL_String16
String container template.
class CL_String8
String container template.
class CL_StringAllocator
Allocate strings in blocks.
class CL_StringData16
String data class for 16 bit data.
class CL_StringData8
String data class for 8 bit data.
class CL_StringFormat
String formatting class.
class CL_StringHelp
String helper functions.
class CL_StringRef16
String reference template.
class CL_StringRef8
String reference template.
class CL_UTF8_Reader
UTF8 reader helper functions.
Namespaces
namespace std
Typedefs
typedef CL_String8 CL_String
typedef CL_StringRef8 CL_StringRef
Functions
CL_String cl_format (const CL_StringRef &format)
template<class Arg1 >
CL_String cl_format (const CL_StringRef &format, Arg1 arg1)
template<class Arg1 , class Arg2 >
CL_String cl_format (const CL_StringRef &format, Arg1 arg1, Arg2 arg2)
template<class Arg1 , class Arg2 , class Arg3 >
CL_String cl_format (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3)
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 >
CL_String cl_format (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4)
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 >
CL_String cl_format (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5)
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 >
CL_String cl_format (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6)
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 >
CL_String cl_format (const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7)
CL_API_CORE void cl_log_event (const CL_StringRef &type, const CL_StringRef &text)
Log text to logger.
template<class Arg1 , class Arg2 , class Arg3 >
void cl_log_event (const CL_StringRef &type, const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3)
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 >
void cl_log_event (const CL_StringRef &type, const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7)
template<class Arg1 >
void cl_log_event (const CL_StringRef &type, const CL_StringRef &format, Arg1 arg1)
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 >
void cl_log_event (const CL_StringRef &type, const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4)
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 >
void cl_log_event (const CL_StringRef &type, const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5)
template<class Arg1 , class Arg2 >
void cl_log_event (const CL_StringRef &type, const CL_StringRef &format, Arg1 arg1, Arg2 arg2)
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 >
void cl_log_event (const CL_StringRef &type, const CL_StringRef &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6)
CL_API_CORE bool operator!= (const CL_StringData8 &s1, const CL_StringData8 &s2)
CL_API_CORE bool operator!= (const char *s1, const CL_StringData8 &s2)
CL_API_CORE bool operator!= (const CL_StringData8 &s1, const char *s2)
CL_API_CORE bool operator!= (const CL_StringData16 &s1, const CL_StringData16 &s2)
CL_API_CORE bool operator!= (const wchar_t *s1, const CL_StringData16 &s2)
CL_API_CORE bool operator!= (const CL_StringData16 &s1, const wchar_t *s2)
CL_API_CORE CL_String16 operator+ (const CL_StringData16 &s1, const CL_StringData16 &s2)
CL_API_CORE CL_String8 operator+ (const CL_StringData8 &s1, const CL_StringData8 &s2)
CL_API_CORE CL_String8 operator+ (const char *s1, const CL_StringData8 &s2)
CL_API_CORE CL_String8 operator+ (const wchar_t *s1, const CL_StringData8 &s2)
CL_API_CORE CL_String8 operator+ (const CL_StringData8 &s1, const char *s2)
CL_API_CORE CL_String16 operator+ (const char *s1, const CL_StringData16 &s2)
CL_API_CORE CL_String8 operator+ (const CL_StringData8 &s1, const wchar_t *s2)
CL_API_CORE CL_String8 operator+ (char c, const CL_StringData8 &s2)
CL_API_CORE CL_String8 operator+ (const CL_StringData8 &s1, char c)
CL_API_CORE CL_String16 operator+ (const wchar_t *s1, const CL_StringData16 &s2)
CL_API_CORE CL_String16 operator+ (const CL_StringData16 &s1, const char *s2)
CL_API_CORE CL_String16 operator+ (const CL_StringData16 &s1, const wchar_t *s2)
CL_API_CORE CL_String16 operator+ (wchar_t c, const CL_StringData16 &s2)
CL_API_CORE CL_String16 operator+ (const CL_StringData16 &s1, wchar_t c)
CL_API_CORE bool operator< (const wchar_t *s1, const CL_StringData16 &s2)
CL_API_CORE bool operator< (const CL_StringData16 &s1, const wchar_t *s2)
CL_API_CORE bool operator< (const CL_StringData8 &s1, const char *s2)
CL_API_CORE bool operator< (const CL_StringData16 &s1, const CL_StringData16 &s2)
CL_API_CORE bool operator< (const char *s1, const CL_StringData8 &s2)
CL_API_CORE bool operator< (const CL_StringData8 &s1, const CL_StringData8 &s2)
CL_API_CORE bool operator== (const CL_StringData16 &s1, const CL_StringData16 &s2)
CL_API_CORE bool operator== (const CL_StringData8 &s1, const char *s2)
CL_API_CORE bool operator== (const wchar_t *s1, const CL_StringData16 &s2)
CL_API_CORE bool operator== (const char *s1, const CL_StringData8 &s2)
CL_API_CORE bool operator== (const CL_StringData16 &s1, const wchar_t *s2)
CL_API_CORE bool operator== (const CL_StringData8 &s1, const CL_StringData8 &s2)
CL_API_CORE bool operator> (const CL_StringData8 &s1, const char *s2)
CL_API_CORE bool operator> (const char *s1, const CL_StringData8 &s2)
CL_API_CORE bool operator> (const CL_StringData8 &s1, const CL_StringData8 &s2)
CL_API_CORE bool operator> (const CL_StringData16 &s1, const wchar_t *s2)
CL_API_CORE bool operator> (const wchar_t *s1, const CL_StringData16 &s2)
CL_API_CORE bool operator> (const CL_StringData16 &s1, const CL_StringData16 &s2)
Typedef Documentation
typedef CL_String8 CL_String
typedef CL_StringRef8 CL_StringRef
Function Documentation
CL_String cl_format (const CL_StringRef & format) [inline]
template<class Arg1 > CL_String cl_format (const CL_StringRef & format, Arg1 arg1)
References CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 > CL_String cl_format (const CL_StringRef & format, Arg1 arg1, Arg2 arg2)
References CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 > CL_String cl_format (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3)
References CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 > CL_String cl_format (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4)
References CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 > CL_String cl_format (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5)
References CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 > CL_String cl_format (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6)
References CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 > CL_String cl_format (const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7)
References CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
CL_API_CORE void cl_log_event (const CL_StringRef & type, const CL_StringRef & text)
Log text to logger.
Referenced by cl_log_event().
template<class Arg1 , class Arg2 , class Arg3 > void cl_log_event (const CL_StringRef & type, const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3)
References cl_log_event(), CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 > void cl_log_event (const CL_StringRef & type, const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7)
References cl_log_event(), CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 > void cl_log_event (const CL_StringRef & type, const CL_StringRef & format, Arg1 arg1)
References cl_log_event(), CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 > void cl_log_event (const CL_StringRef & type, const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4)
References cl_log_event(), CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 > void cl_log_event (const CL_StringRef & type, const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5)
References cl_log_event(), CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 > void cl_log_event (const CL_StringRef & type, const CL_StringRef & format, Arg1 arg1, Arg2 arg2)
References cl_log_event(), CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 > void cl_log_event (const CL_StringRef & type, const CL_StringRef & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6)
References cl_log_event(), CL_StringFormat::get_result(), and CL_StringFormat::set_arg().
CL_API_CORE bool operator!= (const CL_StringData8 & s1, const CL_StringData8 & s2)
CL_API_CORE bool operator!= (const char * s1, const CL_StringData8 & s2)
CL_API_CORE bool operator!= (const CL_StringData8 & s1, const char * s2)
CL_API_CORE bool operator!= (const CL_StringData16 & s1, const CL_StringData16 & s2)
CL_API_CORE bool operator!= (const wchar_t * s1, const CL_StringData16 & s2)
CL_API_CORE bool operator!= (const CL_StringData16 & s1, const wchar_t * s2)
CL_API_CORE CL_String16 operator+ (const CL_StringData16 & s1, const CL_StringData16 & s2)
CL_API_CORE CL_String8 operator+ (const CL_StringData8 & s1, const CL_StringData8 & s2)
CL_API_CORE CL_String8 operator+ (const char * s1, const CL_StringData8 & s2)
CL_API_CORE CL_String8 operator+ (const wchar_t * s1, const CL_StringData8 & s2)
CL_API_CORE CL_String8 operator+ (const CL_StringData8 & s1, const char * s2)
CL_API_CORE CL_String16 operator+ (const char * s1, const CL_StringData16 & s2)
CL_API_CORE CL_String8 operator+ (const CL_StringData8 & s1, const wchar_t * s2)
CL_API_CORE CL_String8 operator+ (char c, const CL_StringData8 & s2)
CL_API_CORE CL_String8 operator+ (const CL_StringData8 & s1, char c)
CL_API_CORE CL_String16 operator+ (const wchar_t * s1, const CL_StringData16 & s2)
CL_API_CORE CL_String16 operator+ (const CL_StringData16 & s1, const char * s2)
CL_API_CORE CL_String16 operator+ (const CL_StringData16 & s1, const wchar_t * s2)
CL_API_CORE CL_String16 operator+ (wchar_t c, const CL_StringData16 & s2)
CL_API_CORE CL_String16 operator+ (const CL_StringData16 & s1, wchar_t c)
CL_API_CORE bool operator< (const wchar_t * s1, const CL_StringData16 & s2)
CL_API_CORE bool operator< (const CL_StringData16 & s1, const wchar_t * s2)
CL_API_CORE bool operator< (const CL_StringData8 & s1, const char * s2)
CL_API_CORE bool operator< (const CL_StringData16 & s1, const CL_StringData16 & s2)
CL_API_CORE bool operator< (const char * s1, const CL_StringData8 & s2)
CL_API_CORE bool operator< (const CL_StringData8 & s1, const CL_StringData8 & s2)
CL_API_CORE bool operator== (const CL_StringData16 & s1, const CL_StringData16 & s2)
CL_API_CORE bool operator== (const CL_StringData8 & s1, const char * s2)
CL_API_CORE bool operator== (const wchar_t * s1, const CL_StringData16 & s2)
CL_API_CORE bool operator== (const char * s1, const CL_StringData8 & s2)
CL_API_CORE bool operator== (const CL_StringData16 & s1, const wchar_t * s2)
CL_API_CORE bool operator== (const CL_StringData8 & s1, const CL_StringData8 & s2)
CL_API_CORE bool operator> (const CL_StringData8 & s1, const char * s2)
CL_API_CORE bool operator> (const char * s1, const CL_StringData8 & s2)
CL_API_CORE bool operator> (const CL_StringData8 & s1, const CL_StringData8 & s2)
CL_API_CORE bool operator> (const CL_StringData16 & s1, const wchar_t * s2)
CL_API_CORE bool operator> (const wchar_t * s1, const CL_StringData16 & s2)
CL_API_CORE bool operator> (const CL_StringData16 & s1, const CL_StringData16 & s2)